apiVersion: apps/v1
kind: Deployment
metadata:
  name: daily-bg
  namespace: aaron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daily-bg
  template:
    metadata:
      labels:
        app: daily-bg
    spec:
      containers:
        - name: daily-bg
          image: asia-east1-docker.pkg.dev/aaron-dev-429414/daily-bg/test:v0.0.2
          ports:
            - containerPort: 50051
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: GRPC_SERVER_CERT
              value: "/etc/grpc/tls/tls.crt"
            - name: GRPC_SERVER_KEY
              value: "/etc/grpc/tls/tls.key"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-pw
                  key: mongodb.account
            - name: MONGO_PW
              valueFrom:
                secretKeyRef:
                  name: mongodb-pw
                  key: mongodb.password
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: mongodb.uri
          volumeMounts:
            - name: grpc-tls
              mountPath: /etc/grpc/tls
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 50051
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: grpc-tls
          secret:
            secretName: k8s-grpc-tls
---
apiVersion: v1
kind: Service
metadata:
  name: daily-bg
  namespace: aaron
spec:
  selector:
    app: daily-bg
  ports:
    - protocol: TCP
      name: grpc
      port: 50051
      targetPort: 50051
