apiVersion: apps/v1
kind: Deployment
metadata:
  name: daily-bg
  namespace: aaron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daily-bg
  template:
    metadata:
      labels:
        app: daily-bg
    spec:
      containers:
        - name: daily-bg
          image: asia-east1-docker.pkg.dev/aaron-dev-429414/daily-bg/test:v0.0.2
          ports:
            - containerPort: 50051
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 50051
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: daily-bg
  namespace: aaron
spec:
  selector:
    app: daily-bg
  ports:
    - protocol: TCP
      name: grpc
      port: 50051
      targetPort: 50051
